spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://team4-database.cwmjuw9z0gli.ap-northeast-2.rds.amazonaws.com:3306/DevDB?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: qwer1234!!
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapper/*.xml
